{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spinnaker-cd-demo.serviceAccountName" . }}
  labels:
{{ include "spinnaker-cd-demo.labels" . | nindent 4 }}
{{- end -}}
